#import "@preview/abbr:0.1.1"
= Discussion
The results of this study demonstrate the feasibility of using #abbr.pla("SSM") to simulate #abbr.a("EEG") activity and examine the neural correlates of decision-making processes. The use cases illustrated how the implemented #link("https://github.com/unfoldtoolbox/UnfoldSim.jl")[UnfoldSim.jl] extension can simulate event overlap in #abbr.a("EEG") data and how deconvolution can effectively remove such overlaps. This highlights its potential as a validation tool for #abbr.a("EEG") analysis methods. Additionally, one use case demonstrated the usability of the extension by kind of replicating aspects of the comment from @Comment2024Fromer, further showcasing its applicability. This highlights how the toolbox extension could be used in research in the future. Therefore the extension serves as a valuable resource for cognitive neuroscience research, allowing researchers to investigate decision-making processes in a modular and flexible manner.

A key discussion point is the extent to which these models can represent aspects of real evidence accumulation processes in #abbr.a("EEG") data. This topic was not examined in detail in this thesis, as the primary focus was on general simulation capabilities and use cases related to event overlap. Consequently, the default model parameters were chosen for broad applicability rather than for biological accuracy.
Among the implemented models, the #abbr.a("KellyModel"), with its additional parameters — such as sensory encoding delay and post-accumulation dynamics — offers the highest potential for biological plausibility. Future studies could optimise its parameters to better mimic real evidence accumulation processes. For instance, model parameters could be systematically adjusted, and simulation outputs iteratively compared with empirical #abbr.a("EEG") data until a high level of similarity is achieved. Successfully replicating real evidence accumulation in #abbr.a("EEG") could pave the way for more realistic analyses of human decision-making processes.

The choice of #abbr.pla("SSM") used in this work was primarily based on the degree of familiarity from the literature and to enable a certain degree of differentiation. In addition to the two selected models #abbr.a("LBA") and #abbr.a("DDM"), there are several other #abbr.pla("SSM") in the literature. However, the extent to which the models also fit well with the topic of evidence accumulation and whether there is a better selection of #abbr.pla("SSM") was not investigated. In this case, it would therefore make sense to consider other models in a future study. The inclusion of alternative models, such as the racing diffusion model @tillman2020sequential or the attentional drift diffusion model @Krajbich2010, could offer additional perspectives on the decision dynamics and further improve the variation of the #abbr.a("EEG") simulations.

A key methodological contribution of this thesis is the use of #abbr.a("EEG") simulations to validate deconvolution techniques. This aligns with an ongoing debate in cognitive neuroscience, highlighted by the conflicting interpretations of @Fromer2024 and @Comment2024Fromer regarding the application of deconvolution in analysing evidence accumulation processes. The use cases presented in this thesis demonstrate how component overlaps in #abbr.a("EEG") data can be simulated and subsequently separated through deconvolution. This approach allows for the systematic investigation of potential misinterpretations, where evidence accumulation signatures may artifactually emerge from stimulus-response overlap.\
Through deconvolution, @Fromer2024's findings suggest that response-locked evidence accumulation patterns — often referred to as the #abbr.a("CPP") effect — previously thought to reflect true accumulation may, in fact, be artifacts of overlapping neural activity. The first two use cases in @subsec:deconv kind of replicated these conditions using simplified simulations. The first case confirmed that if a component contributing to an overlap is genuinely present, it remains after deconvolution. In contrast, the second case showed that when an apparent component is merely the result of overlap and does not truly exist, it disappears after deconvolution. This supports @Fromer2024's findings that if an evidence accumulation process is genuinely present, it should remain detectable after deconvolution. The ability of the #link("https://github.com/unfoldtoolbox/Unfold.jl")[Unfold.jl] extension to replicate these conditions in part supports the researchers to systematically investigate such artefacts and continue the debate.

Nevertheless, only #link("https://github.com/unfoldtoolbox/Unfold.jl")[Unfold's] previous deconvolution method was analysed in the use cases. Another possibility for investigation would be the application of the RIDE algorithm. This is a method for the decomposition, reconstruction, and single trial analysis of #abbr.a("ERP") @Ouyang2015. RIDE allows for the separation of #abbr.a("EEG") components even if they have different latency variability across trials. This is particularly relevant for evidence accumulation processes, where response-locked neural activity may vary in timing due to differences in decision latencies. Therefore RIDE could provide a clearer separation of decision-related #abbr.a("EEG") activity from unrelated neural processes. However, as discussed above, it remains an open question whether the evidence accumulation pattern — #abbr.a("CPP") effect — truly reflects an accumulation process or merely arises from overlapping signals. Applying RIDE in future research could help determine if the pattern persists as an independent signal after decomposition or whether it is an artifact of neural overlap. Resolving this question would provide stronger evidence for or against interpreting the evidence accumulation pattern as a genuine marker of decision-making processes.

Overall, this study underscores the importance of computer-aided modeling in neuroscience and shows how #abbr.a("SSM")-based #abbr.a("EEG") simulations could be used to contribute to a deeper understanding of decision-making processes in the brain. The developed #link("https://github.com/unfoldtoolbox/Unfold.jl")[Unfold.jl] extension not only facilitates theoretical investigations, but also offers practical implications for the design and interpretation of #abbr.a("EEG") experiments in cognitive neuroscience. Furthermore, the modularity and neat documentation make the implementation easy to expand.

= Conclusion
This thesis has demonstrated the feasibility and value of using computational modeling to simulate #abbr.a("EEG") activity in the context of decision-making. By integrating #abbr.pla("SSM") such as #abbr.a("DDM"), #abbr.a("LBA"), and the #abbr.a("KellyModel") into the #link("https://github.com/unfoldtoolbox/UnfoldSim.jl")[UnfoldSim.jl] framework, it provides a structured approach to investigating the neural mechanisms underlying evidence accumulation. The ability to replicate key #abbr.a("EEG") dynamics through these models reinforces their relevance in cognitive neuroscience.

A key insight from this work is that #abbr.a("EEG") simulations can help clarify methodological challenges, particularly in distinguishing true decision-related signals from artifacts caused by overlapping neural activity. The results support the notion that some observed #abbr.a("EEG") correlates of evidence accumulation may be influenced by component overlap rather than reflecting actual decision-making processes. This underscores the necessity of simulation-based validation in #abbr.a("EEG") research.

Beyond its immediate contributions, the #link("https://github.com/unfoldtoolbox/Unfold.jl")[Unfold.jl] extension developed in this thesis establishes a foundation for future studies. Its modular design allows for further expansion, including the refinement of model parameters and the integration of additional decision-making models. However, challenges such as model assumptions and parameter optimization remain, requiring future improvements to enhance biological plausibility.

In conclusion, this work highlights the critical role of computational simulations in advancing #abbr.a("EEG") research on decision-making. By providing a #link("https://github.com/unfoldtoolbox/UnfoldSim.jl")[UnfoldSim.jl] extension which enables rigorous testing and refinement of theories and methods, it contributes to the broader effort of unraveling the complexities of human cognition and neural processing.