#import "@preview/dashy-todo:0.0.1": todo
#import "@preview/abbr:0.1.1"
#import "../src/styles/flex-captions.typ": flex-caption
= Introduction
The human brain continuously processes and integrates sensory information in order to make decisions. This process is typically modelled as evidence accumulation. The complex cognitive function behind this underlies many of our everyday decisions, whether simple or complex. This function is often modelled by #abbr.pla("SSM") @ratcliff1978theory.

The #abbr.pla("SSM"), such as the #abbr.a("DDM"), #abbr.a("LBA") and others, are used to model how information is accumulated over time until a decision threshold is reached. But almost all of their applications are for inference. This means that you have the data and want to access the "hidden" states of the assumed evidence integration model @brown2008linear. Therefore, #abbr.pla("SSM") can offer a useful framework for investigating the neural mechanisms underlying decision-making. By modeling these processes, researchers can compare model-generated predictions with neural data, gaining deeper insights into the temporal dynamics and cognitive processes involved in decision-making. Furthermore, the different parameters of the #abbr.pla("SSM") are typically interpreted as correlates of underlying cognitive processes and thus contribute to a better understanding of the process. Understanding the neural mechanisms underlying the decision-making process is crucial to improve our understanding of cognition and its relationship to brain activity @vanvugt2019cppxdmp@forstmann2016sequential.

The #abbr.pla("SSM") like the #abbr.a("DDM") are mostly used to model behaviour. In contrast, #abbr.a("EEG") can be used to record brain activity during decision making, which provides insight into the temporal aspects of evidence accumulation. The #abbr.a("EEG") data can be analysed to identify neural indicators of the decision-making process over time, particularly those that reflect the accumulation of evidence. In many studies, the #abbr.a("CPP") a specific #abbr.a("EEG") component  has now been identified as an indicator of evidence accumulation during decision-making. This enables the comparison of averaged traces from multiple trials of #abbr.a("SSM") simulations with corresponding #abbr.a("EEG") data @vanvugt2019cppxdmp. 

#abbr.pla("SSM") are widely used to explain behavioural aspects of decision making, but their direct link to neural data remains an open challenge. Conventionally, #abbr.a("EEG") data can be integrated into #abbr.pla("SSM") in two ways: as a predictor influencing the model parameters, or as an explanandum where #abbr.a("EEG") features (e.g. #abbr.a("CPP")) are modelled together with behavioural data such as reaction time and choice. To systematically explore these relationships, a specialised computational framework is required. This computational framework should enable the simulation of #abbr.a("EEG") data based on different #abbr.pla("SSM") in decision-making contexts and facilitate the mapping of model parameters to observable neural activity. Mastering this integration remains a central challenge in cognitive neuroscience @connell2021kelly@forstmann2016sequential.

This thesis aims to provide a computational framework for simulating #abbr.a("EEG") data using different #abbr.pla("SSM") to explore how these models reflect the evidence accumulation process in the brain. The computational framework is to be integrated into the existing Julia package for simulating EEG data _UnfoldSim.jl_ @UnfoldSim and is therefore subsequently referred to as an extension. By systematically manipulating model parameters of the different #abbr.pla("SSM") and and comparing their patterns to patterns observed in the #abbr.a("EEG") literature, researchers can try to find out which model characteristics best reflect the evidence accumulation processes in the brain. Understanding these indicators could lead to more precise interpretations of #abbr.a("EEG") data in the context of cognitive decision-making research.

== Motivation & related work <subsec:motivation>
In the publication "Neurocomputational mechanisms of prior-informed perceptual decision-making in humans" #cite(<Kelly2021notebook>) a novel #abbr.a("SSM") was used to simulate a decision-making process in the brain. This simulation was compared with real #abbr.a("EEG") results from a decision-making experiment. 
The real #abbr.a("EEG") results are shown in the @fig:KellyetalCPP in tile A. The stimulus-locked is shown on the left and the response-locked on the right. Tile B shows the simulated #abbr.a("CPP") for comparison, also stimulus-locked and response-locked. This comparison shows how the #abbr.a("CPP")-#abbr.a("EEG") activity shows markers of an #abbr.a("SSM"), with the activity increasing from an stimulus onset up to a threshold value when the button is pressed. It should be noted that the increasing activity depends on the actual evidence available. Overall, this shows how #abbr.a("EEG") activity reflects #abbr.a("SSM") integration.
#figure(
grid(
  columns: 2,
  rows: 1,
  align: left,
  gutter: 1cm,
  grid.cell([*A*
    #image("graphics/Kelly_et_al_CPP_real.png", width: 80mm)
  ]),
  grid.cell([*B*
    #image("graphics/Kelly_et_al_CPP_sim.png", width: 80mm)
  ])), caption: flex-caption([Stimulus-locked and 
response-locked #abbr.a("CPP") of a decision-making experiment @Kelly2021notebook. Legend: conditions of a motion discrimination task experiment  black=Easy, blue=LoCoh, red=Deadline. Where Easy: High coherence (20%) and a long response deadline (1.6s).
LoCoh (Low Coherence): Lower coherence (~8%) and a long deadline (1.6s).
Deadline: High coherence (20%) but a short deadline (~0.5s). *A)* #abbr.a("ERP") based on real #abbr.a("EEG") data of the experiment. d) stimulus-lockend e) response-locked *B)* simulated #abbr.a("ERP"). k) stimulus-lockend l) response-locked],[Stimulus-locked and 
response-locked CPP of a decision-making experiment @Kelly2021notebook])
)<fig:KellyetalCPP>
In another publication by @Fromer2024, precisely such evidence accumulation #abbr.a("EEG") signals were investigated. In contrast to the earlier findings by Kelly et al., it has been shown that stimulus-locked activity can "mimic" an evidence accumulation process when it is aligned to the response @Fromer2024. This means that neural activity, although appearing to reflect gradual evidence accumulation, may instead be structured in a way that systematically increases up to the response moment, without necessarily reflecting an actual accumulation process. The authors show based on four datasets, that signals of evidence accumulation can arise as an artefact of component overlap. Since the reaction time between the stimulus and the response is sometimes very short, the brain response to the stimulus, the response to the evidence accumulation process and the response to the subjects button press overlap in time. This can result in the ramp-up, without any evidence integration signal being present. Furthermore, the four studies were reanalysed using overlap-correction between stimulus and subjects button press. In all four example the response-locked evidence accumulation patterns disappear. That neural signatures of evidence accumulation can arise from simple overlapping components, sparked discussion in the field @Comment2024Fromer.

The research group led by Kelly et. al. responded with a commentary entitled "Regressing Away Common Neural Choice Signals does not make them Artifacts. Comment on Frömer et al (2024, Nature Human Behaviour)"@Comment2024Fromer to the paper by Frömer et. al.. In this paper, they simulated neural data based on a basic #abbr.a("LBA") to refute the findings of Frömer et. al. Through these simulations, the researchers around Kelly et. al. show that the deconvolution analyses used by Frömer et. al. are not necessarily appropriate to correctly capture limited accumulation signals. They also showed that applying the same analyses to real, increasing, accumulation-to-bound signals is consistent with the empirical results of @Fromer2024 that this can lead to an amplitude reduction effect rather than the alternative scenario in which such signals are not present.@Comment2024Fromer As a result, they argue that the deconvolution analysis used by @Fromer2024 actually removes artefactually correct, truthful neural signatures of evidence accumulation in at least some scenarios, possibly making it a misguided analysis tool. Which means that further investigations into this topic are still open.

This discussion on how decision-making is represented in the brain underscores the value of simulations to adress methodological key questions on the validity of an analysis procedure. However, it also reveals that there is currently no simple modelling framework that enables flexible and comprehensive simulations of these specific time series. This can make a contribution to research into cognitive neuroscience. This emphasises the need for a computational framework that enables flexible and comprehensive simulations based on #abbr.pla("SSM") and thus allows a systematic evaluation of analysis methods. Such a tool is essential for the advancement of cognitive neuroscience, as it can remove ambiguities in the interpretation of neural signals and provide a standardised approach to hypothesis testing. Overcoming these challenges is important to improve our understanding of how decision-making is represented in the brain. In order to gain a deeper understanding and clarify the open questions.